"use strict";

const I18N = {
  "zh-CN": {
    "chat.subagentReportProgress": "下次汇报进度：{{current}} / {{interval}} 次调用 · 累计 {{total}} 次工具调用",
    "chat.subagentReportSummary": "已汇报 {{reports}} 次 · 累计 {{total}} 次工具调用",
    "chat.subagentCallSummary": "累计 {{total}} 次工具调用",
    "chat.subagentReportProgressHint": "分子是本批已结束的工具调用次数；每 {{interval}} 次自动汇报，汇报后重新计数。不是任务完成进度。",
    "chat.subagentReportSummaryHint": "汇报次数指程序已生成的报告份数，不代表主智能体已经阅读。累计调用次数包含执行失败的调用。",
    "chat.subagentIntervalSource.definition": "汇报间隔由用户设置",
    "chat.subagentIntervalSource.dispatch": "汇报间隔由主智能体指定",
    "chat.subagentExecution": "第 {{execution}} 轮执行",
    "chat.subagentReworking": "正在返工 · 第 {{execution}} 轮",
    "chat.subagentRecallReady": "已完成 · 主智能体可召回",
    "chat.subagentRecallCheck": "历史执行 · 召回以当前上下文状态为准",
    "chat.subagentRecallMemoryOnly": "仅保留在当前会话运行实例的内存中；配置切换、实例释放或程序重启后不能恢复上下文。",
    "chat.subagentHistorical": "历史记录 · 当前没有活跃执行",
    "chat.subagentStoppingNow": "正在终止，等待在途操作收束…",
    "chat.subagentGuidingNow": "引导已接收，等待当前工具结束…",
    "chat.stopThisSubagent": "终止此子智能体",
    "chat.subagentRevokingNow": "正在撤销召回资格…",
    "chat.subagentRevokeRecallTooltip": "标记为已停止，撤销跨重启召回资格",
    "chat.subagentRevokeRecall": "撤销未来召回",
    "chat.subagentSegment": "第 {{segment}} 段 · 本段已完成 {{steps}} 次工具调用",
    "chat.subagentStopSource.user": "用户主动终止",
    "chat.subagentStopSource.parent": "主智能体请求终止",
    "chat.subagentStopSource.session": "会话停止或已结束",
    "chat.subagentGuideState.accepted": "引导已接收",
    "chat.subagentGuideState.applying": "正在应用引导",
    "chat.subagentGuideState.applied": "引导已生效",
    "chat.subagentGuideState.cancelled": "引导已取消",
    "chat.subagentGuideState.rejected": "引导被拒绝",
    "chat.subagentLatestReport": "第 {{seq}} 次汇报 · 工具调用 {{from}}–{{to}}",
    "chat.subagentReportedStatement": "子智能体陈述：",
    "chat.subagentReportTruncated": "摘要已截取，可在执行记录中查看完整工具输出。",
    "chat.subagentStepStatus.running": "执行中",
    "chat.subagentStepStatus.success": "成功",
    "chat.subagentStepStatus.error": "失败",
    "chat.subagentStepStatus.aborted": "已取消",
    "chat.subagentSourceMemory": "内存",
    "chat.subagentSourceDisk": "磁盘",
    "chat.subagentSnapshotVersion": "快照 v{{version}}",
    "chat.subagentPersistenceState.memory-only": "可召回 · 内存",
    "chat.subagentPersistenceState.saving": "正在保存",
    "chat.subagentPersistenceState.durable-ready": "可召回 · 已保存",
    "chat.subagentPersistenceState.pending-validation": "待校验",
    "chat.subagentPersistenceState.blocked": "配置不兼容",
    "chat.subagentPersistenceState.revoked": "已停止（已撤销）",
    "chat.subagentPersistenceState.interrupted": "执行中断",
    "chat.subagentPersistenceState.failed": "执行失败",
    "chat.subagentPersistenceState.unavailable": "快照不可用",
    "chat.subagentPersistenceState.persistence-error": "保存失败",
    "chat.subagentPersistenceState.cleaned": "已清理",
  },
  "en": {
    "chat.subagentReportProgress": "Next report: {{current}} / {{interval}} calls · {{total}} total tool calls",
    "chat.subagentReportSummary": "Reports sent: {{reports}} · {{total}} total tool calls",
    "chat.subagentCallSummary": "Total tool calls: {{total}}",
    "chat.subagentReportProgressHint": "The numerator counts finished tool calls in this batch. A report is generated every {{interval}} calls, then the count resets. This is not task completion progress.",
    "chat.subagentReportSummaryHint": "Report count means reports generated by the runtime, not confirmed as read by the main agent. Total tool calls include failed calls.",
    "chat.subagentIntervalSource.definition": "Report interval set by the user",
    "chat.subagentIntervalSource.dispatch": "Report interval set by the main agent",
    "chat.subagentExecution": "Execution {{execution}}",
    "chat.subagentReworking": "Reworking · Execution {{execution}}",
    "chat.subagentRecallReady": "Completed · Available for parent recall",
    "chat.subagentRecallCheck": "Past execution · Recall depends on retained context",
    "chat.subagentRecallMemoryOnly": "Context exists only in the current session runtime's memory. Configuration changes, runtime release or application restart cannot restore it.",
    "chat.subagentHistorical": "Historical record · no active execution",
    "chat.subagentStoppingNow": "Stopping; waiting for in-flight operations…",
    "chat.subagentGuidingNow": "Guidance queued; waiting for the current tool…",
    "chat.stopThisSubagent": "Stop this subagent",
    "chat.subagentRevokingNow": "Revoking recall eligibility…",
    "chat.subagentRevokeRecallTooltip": "Mark as stopped to revoke cross-restart recall eligibility",
    "chat.subagentRevokeRecall": "Revoke future recall",
    "chat.subagentSegment": "Segment {{segment}} · {{steps}} completed tool calls",
    "chat.subagentStopSource.user": "Stopped by the user",
    "chat.subagentStopSource.parent": "Stop requested by the main agent",
    "chat.subagentStopSource.session": "Session stopped or ended",
    "chat.subagentGuideState.accepted": "Guidance accepted",
    "chat.subagentGuideState.applying": "Applying guidance",
    "chat.subagentGuideState.applied": "Guidance applied",
    "chat.subagentGuideState.cancelled": "Guidance cancelled",
    "chat.subagentGuideState.rejected": "Guidance rejected",
    "chat.subagentLatestReport": "Report #{{seq}} · Tool calls {{from}}–{{to}}",
    "chat.subagentReportedStatement": "Subagent statement:",
    "chat.subagentReportTruncated": "Summary truncated. Full tool output is available in the execution records.",
    "chat.subagentStepStatus.running": "Running",
    "chat.subagentStepStatus.success": "Succeeded",
    "chat.subagentStepStatus.error": "Failed",
    "chat.subagentStepStatus.aborted": "Cancelled",
    "chat.subagentSourceMemory": "Memory",
    "chat.subagentSourceDisk": "Disk",
    "chat.subagentSnapshotVersion": "Snapshot v{{version}}",
    "chat.subagentPersistenceState.memory-only": "Recallable · Memory",
    "chat.subagentPersistenceState.saving": "Saving snapshot",
    "chat.subagentPersistenceState.durable-ready": "Recallable · Saved",
    "chat.subagentPersistenceState.pending-validation": "Pending validation",
    "chat.subagentPersistenceState.blocked": "Configuration incompatible",
    "chat.subagentPersistenceState.revoked": "Stopped (Revoked)",
    "chat.subagentPersistenceState.interrupted": "Execution interrupted",
    "chat.subagentPersistenceState.failed": "Execution failed",
    "chat.subagentPersistenceState.unavailable": "Snapshot unavailable",
    "chat.subagentPersistenceState.persistence-error": "Persistence error",
    "chat.subagentPersistenceState.cleaned": "Snapshot cleaned",
  },
};

function translate(locale, key, params = {}) {
  const normLocale = typeof locale === "string" && locale.toLowerCase().startsWith("zh") ? "zh-CN" : "en";
  const dict = I18N[normLocale] || I18N["zh-CN"];
  let template = dict[key] || I18N["zh-CN"][key] || I18N["en"][key] || key;
  if (params && typeof params === "object") {
    for (const [k, v] of Object.entries(params)) {
      if (v !== undefined && v !== null) {
        template = template.replaceAll(`{{${k}}}`, String(v));
      }
    }
  }
  return template;
}

function normalizeCollaboration(data) {
  if (!data || typeof data !== "object") return undefined;
  if (Number.isSafeInteger(data.reportIntervalSteps) && data.reportIntervalSteps > 0) {
    return data;
  }
  return undefined;
}

function canStopSubagent({ id, sessionId, live, running, phase }) {
  return Boolean(id && sessionId && live && running && phase !== "finished");
}

function canRevokeRecall({ id, sessionId, running, execution, recall }) {
  const resumable = Boolean(recall?.canResume && recall.execution === execution);
  return Boolean(
    !running &&
      id &&
      sessionId &&
      recall?.source === "disk" &&
      execution !== undefined &&
      recall.execution === execution &&
      (recall?.status === "completed" || recall?.persistenceState === "durable-ready" || resumable) &&
      recall?.persistenceState !== "revoked" &&
      recall?.status !== "aborted" &&
      recall?.status !== "stopped",
  );
}

async function renderSupervision(context, { desktopInvoke } = {}) {
  if (!context || typeof context !== "object") return null;

  const id = typeof context.delegationId === "string" ? context.delegationId.trim() : "";
  if (!id) return null;

  const sessionId = typeof context.sessionId === "string" ? context.sessionId.trim() : "";
  const running = Boolean(context.running);
  const live = Boolean(context.live);
  const compact = Boolean(context.compact);
  const locale = context.locale || "zh-CN";

  const data = normalizeCollaboration(context.collaboration);
  const execution = Number.isSafeInteger(context.execution)
    ? context.execution
    : Number.isSafeInteger(data?.execution)
      ? data.execution
      : undefined;

  let recall = undefined;
  if (!running && id && sessionId && typeof desktopInvoke === "function") {
    try {
      recall = await desktopInvoke("subagent/recallStatus", [{ sessionId, delegationId: id }]);
    } catch {
      // 查询失败不能把历史快照当成可召回的活实例，不提供撤销按钮
      recall = undefined;
    }
  }

  const resumable = Boolean(recall?.canResume && recall.execution === execution);
  const stopping = Boolean(live && running && (context.requested || data?.phase === "stopping"));
  const canStop = canStopSubagent({ id, sessionId, live, running, phase: data?.phase });
  const canRevoke = canRevokeRecall({ id, sessionId, running, execution, recall });

  const reportInProgress = Boolean(live && running && !stopping && data?.phase !== "finished");
  const reportCount = data?.latestReport?.reportSeq ?? (data?.completedSteps === 0 ? 0 : undefined);

  const statusCopyChildren = [];

  if (data) {
    const hintKey = reportInProgress ? "chat.subagentReportProgressHint" : "chat.subagentReportSummaryHint";
    const title = `${translate(locale, hintKey, { interval: data.reportIntervalSteps })} · ${translate(locale, `chat.subagentIntervalSource.${data.intervalSource}`)}`;
    const summaryKey = reportInProgress
      ? "chat.subagentReportProgress"
      : reportCount !== undefined
        ? "chat.subagentReportSummary"
        : "chat.subagentCallSummary";
    const text = translate(locale, summaryKey, {
      current: data.stepsSinceReport,
      interval: data.reportIntervalSteps,
      total: data.completedSteps,
      reports: reportCount,
    });
    statusCopyChildren.push({
      kind: "text",
      key: "report-summary",
      title,
      text,
    });
  }

  if (execution) {
    const execKey = running && execution > 1 ? "chat.subagentReworking" : "chat.subagentExecution";
    statusCopyChildren.push({
      kind: "text",
      key: "execution-counter",
      text: translate(locale, execKey, { execution }),
    });
  }

  if (!running && (execution !== undefined || recall)) {
    const stateText = recall?.persistenceState
      ? translate(locale, `chat.subagentPersistenceState.${recall.persistenceState}`)
      : translate(locale, resumable ? "chat.subagentRecallReady" : "chat.subagentRecallCheck");
    const badges = [stateText];
    if (recall?.source && recall.persistenceState !== "memory-only" && recall.persistenceState !== "durable-ready") {
      badges.push(translate(locale, recall.source === "disk" ? "chat.subagentSourceDisk" : "chat.subagentSourceMemory"));
    }
    if (recall?.snapshotVersion !== undefined) {
      badges.push(translate(locale, "chat.subagentSnapshotVersion", { version: recall.snapshotVersion }));
    }
    const tooltip = recall?.reason
      ? (recall.snapshotVersion !== undefined
          ? `${translate(locale, "chat.subagentSnapshotVersion", { version: recall.snapshotVersion })} · ${recall.reason}`
          : recall.reason)
      : (recall?.source === "memory" ? translate(locale, "chat.subagentRecallMemoryOnly") : undefined);

    statusCopyChildren.push({
      kind: "text",
      key: "persistence-status",
      text: badges.join(" · "),
      ...(tooltip ? { title: tooltip } : {}),
    });
  }

  if (!live && running) {
    statusCopyChildren.push({
      kind: "text",
      key: "live-historical",
      text: translate(locale, "chat.subagentHistorical"),
    });
  } else if (stopping) {
    statusCopyChildren.push({
      kind: "text",
      key: "live-stopping",
      text: translate(locale, "chat.subagentStoppingNow"),
    });
  } else if (data?.phase === "guiding") {
    statusCopyChildren.push({
      kind: "text",
      key: "live-guiding",
      text: translate(locale, "chat.subagentGuidingNow"),
    });
  }

  const statusRowChildren = [
    {
      kind: "row",
      key: "status-copy",
      children: statusCopyChildren,
    },
  ];

  if (canStop) {
    statusRowChildren.push({
      kind: "action",
      key: "action-stop",
      action: "stop",
      icon: "stop",
      disabled: stopping,
      text: translate(locale, "chat.stopThisSubagent"),
      title: translate(locale, stopping ? "chat.subagentStoppingNow" : "chat.stopThisSubagent"),
    });
  }

  if (canRevoke) {
    statusRowChildren.push({
      kind: "action",
      key: "action-revoke",
      action: "revoke",
      icon: "stop",
      disabled: false,
      text: translate(locale, "chat.subagentRevokeRecall"),
      title: translate(locale, "chat.subagentRevokeRecallTooltip"),
    });
  }

  const rootChildren = [
    {
      kind: "row",
      key: "status-bar",
      children: statusRowChildren,
    },
  ];

  if (!compact && data) {
    const detailChildren = [];

    detailChildren.push({
      kind: "text",
      key: "detail-segment",
      text: translate(locale, "chat.subagentSegment", { segment: data.segmentId, steps: data.segmentCompletedSteps }),
    });

    detailChildren.push({
      kind: "text",
      key: "detail-interval-source",
      text: translate(locale, `chat.subagentIntervalSource.${data.intervalSource}`),
    });

    if (data.stopSource) {
      detailChildren.push({
        kind: "text",
        key: "detail-stop-source",
        text: translate(locale, `chat.subagentStopSource.${data.stopSource}`),
      });
    }

    if (recall?.reason) {
      detailChildren.push({
        kind: "text",
        key: "detail-recall-reason",
        text: recall.reason,
        title: recall.reason,
      });
    }

    if (data.latestGuide) {
      detailChildren.push({
        kind: "text",
        key: "detail-guide-state",
        text: translate(locale, `chat.subagentGuideState.${data.latestGuide.status}`),
        title: data.latestGuide.instruction,
      });
    }

    if (data.latestReport) {
      const reportSummaryTitle = translate(locale, "chat.subagentLatestReport", {
        seq: data.latestReport.reportSeq,
        from: data.latestReport.fromStep,
        to: data.latestReport.toStep,
      });

      const reportChildren = [];

      let timeStr = "";
      try {
        timeStr = new Date(data.latestReport.capturedAt).toLocaleString(locale);
      } catch {
        timeStr = String(data.latestReport.capturedAt);
      }
      reportChildren.push({
        kind: "text",
        key: "report-captured",
        text: `${timeStr} · ${data.latestReport.summary}`,
      });

      if (data.latestReport.statement) {
        reportChildren.push({
          kind: "text",
          key: "report-statement",
          text: `${translate(locale, "chat.subagentReportedStatement")} ${data.latestReport.statement}`,
        });
      }

      if (Array.isArray(data.latestReport.steps) && data.latestReport.steps.length > 0) {
        const items = data.latestReport.steps.map((step) => {
          const stepStatusText = translate(locale, `chat.subagentStepStatus.${step.status}`);
          return {
            kind: "item",
            key: step.toolCallId || String(step.seq),
            children: [
              {
                kind: "text",
                text: `#${step.seq} ${step.toolName} · ${stepStatusText}`,
              },
              {
                kind: "pre",
                text: `${step.args || ""}\n${step.result || ""}`,
              },
            ],
          };
        });
        reportChildren.push({
          kind: "list",
          key: "report-steps",
          children: items,
        });
      }

      if (data.latestReport.truncated) {
        reportChildren.push({
          kind: "text",
          key: "report-truncated",
          text: translate(locale, "chat.subagentReportTruncated"),
        });
      }

      detailChildren.push({
        kind: "details",
        key: "detail-latest-report",
        text: reportSummaryTitle,
        children: reportChildren,
      });
    }

    rootChildren.push({
      kind: "row",
      key: "detail-bar",
      children: detailChildren,
    });
  }

  return {
    kind: "column",
    key: "supervision-root",
    children: rootChildren,
  };
}

async function handleSupervisionAction(context, action, { desktopInvoke, getSessionSnapshot } = {}) {
  if (!context || typeof context !== "object") {
    throw new Error("context is required");
  }
  const sessionId = typeof context.sessionId === "string" ? context.sessionId.trim() : "";
  const delegationId = typeof context.delegationId === "string" ? context.delegationId.trim() : "";
  if (!sessionId || !delegationId) {
    throw new Error("sessionId and delegationId are required");
  }
  if (typeof desktopInvoke !== "function") {
    throw new Error("desktopInvoke helper is required");
  }

  const expectedExecution = Number.isSafeInteger(context.execution)
    ? context.execution
    : Number.isSafeInteger(context.collaboration?.execution)
      ? context.collaboration.execution
      : undefined;

  if (action === "stop") {
    // 原始 running 取 context
    if (!context.running || !context.live) {
      throw new Error("Cannot stop a non-running or historical subagent");
    }
    if (context.collaboration?.phase === "finished") {
      throw new Error("Subagent execution has already finished");
    }

    // 使用 getSessionSnapshot 辅助确认宿主最新运行状态
    if (typeof getSessionSnapshot === "function") {
      const snapshot = await getSessionSnapshot({ sessionId });
      if (!snapshot || typeof snapshot !== "object") {
        throw new Error("Failed to obtain session snapshot");
      }
      const sessionStatus = snapshot.session?.status;
      if (sessionStatus !== "running" && sessionStatus !== "waiting_permission") {
        throw new Error("Session is no longer running");
      }
      const activeTurnId = snapshot.session?.activeTurnId ?? snapshot.activeTurn?.id;
      if (context.parentTurnId && activeTurnId && context.parentTurnId !== activeTurnId) {
        throw new Error("Turn mismatch: subagent is historical");
      }
    }

    const input = { sessionId, delegationId };
    if (expectedExecution !== undefined) {
      input.expectedExecution = expectedExecution;
    }
    return desktopInvoke("subagent/stop", [input]);
  }

  if (action === "revoke") {
    if (context.running) {
      throw new Error("Cannot revoke recall while subagent is running");
    }
    if (expectedExecution === undefined) {
      throw new Error("Execution version is required to revoke recall");
    }

    // 重新通过 subagent/recallStatus 检查执行版本和持久化状态
    let recall;
    try {
      recall = await desktopInvoke("subagent/recallStatus", [{ sessionId, delegationId }]);
    } catch {
      throw new Error("Failed to query subagent recall status");
    }

    if (!recall || recall.execution !== expectedExecution) {
      throw new Error("Subagent execution mismatch or recall not found");
    }
    if (recall.source !== "disk") {
      throw new Error("Only disk-persisted subagents can have their recall revoked");
    }
    if (recall.persistenceState === "revoked" || recall.status === "aborted" || recall.status === "stopped") {
      throw new Error("Subagent recall is already revoked or stopped");
    }

    const resumable = Boolean(recall.canResume && recall.execution === expectedExecution);
    const canRevoke = recall.status === "completed" || recall.persistenceState === "durable-ready" || resumable;
    if (!canRevoke) {
      throw new Error("Subagent is not in a recallable state");
    }

    const input = { sessionId, delegationId, expectedExecution };
    await desktopInvoke("subagent/stop", [input]);
    let updated;
    try {
      updated = await desktopInvoke("subagent/recallStatus", [{ sessionId, delegationId }]);
    } catch {
      updated = null;
    }
    return { ok: true, recall: updated };
  }

  throw new Error(`Unsupported action: ${action}`);
}

module.exports = {
  I18N,
  translate,
  normalizeCollaboration,
  canStopSubagent,
  canRevokeRecall,
  renderSupervision,
  handleSupervisionAction,
};
