import { APP_VERSION, APP_DISPLAY_VERSION } from "./app-build.js";
import { resolveChangelogLocale, type ChangelogEntry, type ChangelogLocale } from "./changelog.js";

const stampDate = APP_DISPLAY_VERSION.slice(0, 8);
const date = `${stampDate.slice(0, 4)}-${stampDate.slice(4, 6)}-${stampDate.slice(6, 8)}`;
const entry = (highlights: string[]): ChangelogEntry[] => [{ version: APP_VERSION, date, highlights }];
const zh = entry([
  "修复已保存的子代理快照误报不可用，保存完成后更新卡片状态，并支持手动刷新查询结果。",
  "重构子代理快照保存与恢复：后台保存失败不阻断任务，优先使用内存续跑，快照不可用时提供已有结果供继续处理。",
  "修复新版运行库扩展字段导致的快照保存失败，移除历史指纹变化引起的整会话隔离，并简化保存设置说明。",
  "统一上下文溢出错误识别，避免超长请求被误判为临时故障而反复重试，保留主代理与子代理的压缩恢复。",
  "改善 Windows 插件下载的证书吊销查询容错，校准插件权限风险标识，并为失效的生图模型选择显示错误反馈。",
  "修复侧栏菜单在窗口底部被截断，以及 Windows 窗口恢复后圆角丢失的问题。",
  "恢复首条消息自动标题，保留手动标题优先及命名插件后续优化；提示词增强继续由可选插件提供。",
  "升级 Pi 1.1.0，改进响应计时和上下文估算，保留独立压缩模型、原生搜索与 TaskResume。",
  "全局和项目指令分别分配读取预算，截断时明确提示；修复系统事件重建后的重复记录。",
  "插件网络请求支持跟随、手动或拒绝重定向；修复 Git Bash 临时目录路径并明确超时反馈。",
  "优化模型设置顺序、导入说明和备用模型名称，保留逐模型思考配置；避免生图结果重复展示。",
  "数据库跟随上游升级到 schema 23，迁移前自动备份，并持久记录标题来源以保护手动命名。",
  "添加服务支持插件提供商与动态模型发现；插件安装更快回退下载，继续保留官方、GitHub、CNB 和自定义来源。",
  "修复 Windows Python MCP 启动和文件链接，点击项目文件可按需启动文件管理器；临时会话扩展使用正确工作目录。",
  "阻止 Edit 将文件移动到自身，并按真实文件路径统一编辑失败计数。",
  "代码高亮改由独立 Worker 执行，异常或超时自动显示纯文本，修复 Go 工具输出导致整个界面卡死。",
  "Read 和 Edit 支持带 BOM 的 UTF-16 文本，编辑后保留原编码和换行符。",
  "各子代理独立计算编辑失败次数，失败不再干扰主代理与其他任务，继续保留 TaskResume。",
  "退出前等待重新生成回答的历史归档，并优化会话排序索引。",
  "新增默认关闭的 Jev 结构化分类服务，可从添加服务入口校验密钥并启用；统一账号生图候选选择与保存。",
  "图片附件保留在撰写时的位置，模型请求、当前轮引导和历史对话使用相同顺序，并继续支持 Gemini 音视频输入。",
  "支持使用已登录的 ChatGPT 账号生成和编辑图片，保留现有生图模型与默认选择。",
  "插件提供商支持 OAuth 登录、令牌刷新和退出登录，继续隔离插件托管配置与手动导入导出。",
  "模型和市场请求遵循系统代理与 PAC 配置，改善技能市场混合 DNS 地址的下载兼容性。",
  "MCP 子进程按会话工作目录分别缓存，支持项目目录、临时工作目录和会话 scratch。",
  "大型工具输出分页显示，文件工具避免阻塞宿主异步线程，插件面板加载超时会明确报错。",
  "修复问答卡片排版、图标属性与跨会话 scratch 文件引用，保留批注、侧边对话和任务统计。",
  "定时任务可独立保存项目、模型、思考档位及权限模式。",
  "Codex OAuth 支持按模型启用原生联网搜索，账号模型列表从对应厂商加载，并改进模型目录匹配。",
  "保护连续输入的新草稿与排队附件，恢复失效轮次引用的历史消息，并在界面进程异常退出后重新加载。",
  "改进 WebDAV 配置、请求头输入和插件包内主题资源；云同步与远程主机仅在开发构建且开启开发者模式时显示。",
  "修复子代理派发与会话保存并发时的登记失败，登记成功后连续派发不再重复校验转录。",
  "新增加密 WebDAV 配置云同步，支持同步进度、冲突处理和历史恢复，包含本 fork 的外观与独立压缩模型设置。",
  "支持多个生图候选模型和默认模型选择，默认开启宽松网络以连接局域网及自建服务。",
  "改进压缩失败后的最近上下文保留、超长摘要分块及原生搜索历史续跑，增加启动超时恢复。",
  "修复定时任务调度、附件预览、公式复制和输入交互，Windows 便携版继续使用单文件 EXE。",
  "子智能体支持上下文预算、自动压缩与超限提示，模型预算优先采用用户填写的有效上下文窗口。",
  "新增可选的模型无限重试，以及项目和全局 SYSTEM.md、APPEND_SYSTEM.md 提示词支持。",
  "优化执行过程多级折叠、思考滑条和工具展示，修复预览会话隔离、草稿附件和默认模型保存。",
  "采用 Pi 1.1.0 运行时与应用内压缩适配，保留独立压缩模型、工具激活恢复和 TaskResume。",
  "以编译日期和时间记录本 fork 版本。",
  "独立的安装身份、缓存与更新来源，继续共用原有对话、配置和插件数据。",
  "统一使用小恐龙图标，内置 Windows 黑屏修正版终端。",
]);
const en = entry([
  "Fix saved subagent snapshots incorrectly appearing unavailable, refresh cards after saving, and allow manual status refresh.",
  "Refactor subagent snapshot saving and recovery: background storage failures do not block tasks, continuation prefers memory, and existing results remain available when snapshots cannot be restored.",
  "Fix snapshot failures caused by new runtime metadata, remove session-wide isolation on transcript changes, and simplify persistence settings text.",
  "Align context-overflow classification to avoid transient retries of oversized requests while preserving parent and subagent compaction recovery.",
  "Improve Windows plugin-download tolerance for offline revocation checks, align permission risk labels and report stale image-model selections.",
  "Keep sidebar menus reachable near the viewport bottom and restore Windows window corners after visibility changes.",
  "Restore first-prompt titles while preserving manual names and later plugin refinement; keep prompt enhancement in an optional plugin.",
  "Upgrade to Pi 1.1.0 with improved response timing and context estimates while retaining dedicated compaction, hosted search and TaskResume.",
  "Give global and project instructions separate budgets with explicit truncation notices, and deduplicate restored system events.",
  "Support follow, manual and error redirect modes for plugin requests; fix Git Bash scratch paths and clarify timeout feedback.",
  "Improve model-setting order, import guidance and fallback-model labels while retaining per-model reasoning settings; avoid duplicate generated-image previews.",
  "Upgrade to upstream schema 23 with pre-migration backups and persistent title sources that protect manual names.",
  "Add plugin providers and dynamic model discovery to Add Service; speed up install fallback while keeping official, GitHub, CNB and custom sources.",
  "Fix Windows Python MCP launching and file links, start the file manager on demand, and use the correct directory for temporary-session extensions.",
  "Reject Edit moves to the same file and track edit failures by canonical file identity.",
  "Run syntax highlighting in an isolated worker with a plain-text fallback on errors or timeouts, fixing Go tool output freezing the window.",
  "Read and edit BOM-marked UTF-16 text while preserving its encoding and line endings.",
  "Isolate each delegate's edit failure budget from the parent and other tasks while retaining TaskResume.",
  "Wait for regenerated-answer archival before quitting and optimize session sorting indexes.",
  "Add an opt-in Jev structured classifier with a checked key from Add Service, and align account image-model selection with saving.",
  "Keep image attachments at their draft positions across requests, steering and restored history while retaining Gemini audio and video input.",
  "Generate and edit images with a signed-in ChatGPT account while preserving existing image models and defaults.",
  "Support plugin-provider OAuth sign-in, token refresh and sign-out while isolating managed configuration from manual imports and exports.",
  "Route model and marketplace requests through system proxy and PAC settings, and improve mixed-DNS skill downloads.",
  "Cache MCP child processes by session workspace, including projects, temporary directories and session scratch.",
  "Page large tool output, keep file operations off asynchronous host workers and report plugin panel load timeouts.",
  "Fix question layout, SVG props and cross-session scratch links while retaining annotations, side conversations and task statistics.",
  "Give scheduled tasks their own project, model, reasoning level and permission settings.",
  "Enable opt-in native web search for Codex OAuth and load account models from vendor endpoints with improved catalog matching.",
  "Preserve newer drafts and queued attachments, recover stale transcript references and reload the window after renderer crashes.",
  "Improve WebDAV setup, request-header input and package-local themes; show cloud sync and remote hosts only in developer-enabled development builds.",
  "Fix subagent registration during concurrent session saves and avoid repeated transcript validation after successful registration.",
  "Add encrypted WebDAV configuration sync with progress, conflict handling and history restore, including fork appearance and dedicated compaction-model settings.",
  "Support multiple image-generation candidates and a default selection; enable relaxed networking by default for LAN and self-hosted services.",
  "Improve recent-context retention after failed compaction, chunked summaries and hosted-search continuation; add startup timeout recovery.",
  "Fix scheduled dispatch, attachment previews, formula copying and input interactions; retain the single-file EXE for Windows portable builds.",
  "Support subagent context budgets, automatic compaction and overflow reporting; prioritize user-configured context windows.",
  "Add optional unlimited provider retries and project/global SYSTEM.md and APPEND_SYSTEM.md prompt support.",
  "Improve nested process disclosure, the reasoning slider and tool display; fix preview session isolation, draft attachments and default-model saving.",
  "Use Pi 1.1.0 with application-owned compaction while retaining a dedicated compaction model, deferred tools and TaskResume.",
  "Version this fork by its build date and time.",
  "Separate installation identity, caches and updates while sharing existing conversations, settings and plugin data.",
  "Use the dinosaur icon and bundle the terminal with the Windows output fix.",
]);

/** 本 fork 从日期构建版重新记版本；原项目历史保留在 changelog 文件中。 */
export const FORK_CHANGELOG: Record<ChangelogLocale, readonly ChangelogEntry[]> = {
  "zh-CN": zh,
  en,
};

export function formatForkChangelogNotes(version: string | undefined, locale?: string | null): string | undefined {
  const match = FORK_CHANGELOG[resolveChangelogLocale(locale)].find((item) => item.version === version);
  return match?.highlights.map((line) => `• ${line}`).join("\n");
}
